# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'
max_jobs: 1
image: WMF 5
clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version: master
  au_push: true

  # Github token to commit pushed packages to repository
  github_user_repo: sippi90/chocolateyautomaticpackages
  github_api_key:
    secure: B1rQI7iabDwq+lsHW7CGqBy9k7eRNzuGn9kQ+LhsWxcc7IcRHzTudUMgZNE8Q+nT #https://ci.appveyor.com/tools/encrypt


  # Mail credentials - for error notifications
  mail_user:
    secure: hHZYivZjd6iMBW2a9GjbC2wmzQ3cChXZOYCtLyTgaz4= # https://ci.appveyor.com/tools/encrypt
  mail_pass:
    secure: cqrvCTCZ2fxibyoH+0c/iA== #https://ci.appveyor.com/tools/encrypt
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id: a80d008be848e4754c459284f24be9fa

  # Chocolatey API key - to push updated packages
  api_key:
    secure: MnTUBuZcq79j6jyHwaFGhWjLM+CK94LW1kBzebRsa0ILSKwdpeb+TupaB/C07E5B # https://ci.appveyor.com/tools/encrypt

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name  "Chocolatey"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- ps: |
    $x=$null; $is_branch = ($Env:au_version -ne $null) -and ([version]::TryParse($Env:au_version, [ref]$x) -eq $false)
    if ($is_branch) {
        pushd ..
            git clone -q https://github.com/majkinetor/au.git
            cd au
            git fetch
            git checkout -q $Env:au_version
            ./build.ps1 -Install -NoChocoPackage
        popd
    } else {
        Install-PackageProvider -Name NuGet -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

        $params = @{ Name = 'au' }
        if ( $Env:au_version -ne $null ) { $params.MinimumVersion = $Env:au_version }
        Install-Module @params

        Get-Module au -ListAvailable | select Name, Version
    }

build_script:
- ps: |
    if ( ($Env:APPVEYOR_REPO_COMMIT_MESSAGE -match '\[AU (.+?)\]') -and
         ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') -and
         ($Env:APPVEYOR_FORCED_BUILD -ne 'true')
    ) { $forced = $Matches[1] }

    ./update_all.ps1 -ForcedPackages $forced

    7z a au_temp.zip $Env:TEMP\chocolatey\au\*

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md
- path: au_temp.zip

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
